# Generated by Django 2.0.3 on 2018-04-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_custommodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sn05',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn13',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn15',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn28',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn33',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn34',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn44',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn48',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn66',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn7b',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn83',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
        migrations.AlterField(
            model_name='sn89',
            name='Time',
            field=models.DateTimeField(verbose_name='Time data was recorded'),
        ),
    ]
